name: Create Issue from Template

on:
  workflow_dispatch:
    inputs:
      title:
        description: "Issue title"
        required: true
        type: string
      description:
        description: "Issue description"
        required: false
        type: string
      priority:
        description: "Priority of the issue"
        required: false
        default: "Medium"
        type: string

jobs:
  create-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Create issue
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const issueTitle = core.getInput('title');
            const issueDescription = core.getInput('description') || '';
            const issuePriority = core.getInput('priority');

            const issueBody = `
            ### Issue Description
            ${issueDescription}

            ### Priority
            ${issuePriority}
            
            ### Additional Information
            This issue was created using a GitHub Actions template.
            `;

            const response = await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: issueTitle,
              body: issueBody,
            });

            core.setOutput('issue-url', response.data.html_url);
